### ISSUE TITLE
How to commit and push

### ISSUE THREAD

**Issue by chronosZK** [smashita/CPT341SDA#13]
Can I know how to push the modified code? When I click push, a dialog required user and password is pop up. What should i fill inside the user and password field?

![image](https://user-images.githubusercontent.com/43541506/46083390-ed66d600-c1d3-11e8-9371-54b1c04e1702.png)

**Comment by chuazhe** [comment]
Try putting your github username and password

**Comment by chronosZK** [comment]
> Try putting your github username and password

![image](https://user-images.githubusercontent.com/43541506/46085143-ea6de480-c1d7-11e8-8ac0-609d0376e53c.png)

An error dialog pop up like this

**Comment by chuazhe** [comment]
I think you still don't have the right to commit and push into the repository as a contributor, try opening your email associated with your github account and accept the invitation
![1234567](https://user-images.githubusercontent.com/38622580/46088655-6d466d80-c1df-11e8-8ca1-bcbfafa257d0.PNG)

**Comment by chronosZK** [comment]
Thanks. The problem is solved.
