### ISSUE TITLE
Null could not be edited message

### ISSUE THREAD

**Issue by chronosZK** [smashita/CPT341SDA#14]
![image](https://user-images.githubusercontent.com/43541506/46084687-d2e22c00-c1d6-11e8-9744-0ca8f2a792cb.png)

The null could not be edited message should be displayed when users selecting a non-existing number of recipe to edit and back to main menu.

**Comment by HatsyRei** [comment]
Fixed: https://github.com/smashita/CPT341SDA/pull/40
