### ISSUE TITLE
Problem in Edit Function

### ISSUE THREAD

**Issue by jiechen0824** [smashita/CPT341SDA#18]
![image](https://user-images.githubusercontent.com/43567262/46217512-c267b800-c374-11e8-9d24-edd51b91c7ad.png)

The "nullcould not be edited" message should be come out first after user choosing option "3-Edit a recipe" as the inventory is empty.

**Comment by chronosZK** [comment]
Same problem as #14

**Comment by HatsyRei** [comment]
Fixed: https://github.com/smashita/CPT341SDA/pull/40
