### ISSUE TITLE
Cannot add inventory successfully

### ISSUE THREAD

**Issue by anisahwhb97** [smashita/CPT341SDA#21]
After added the unit of each ingredients. Number of unit of 2 ingredients which are Sugar and Chocolate is not updated
![screenshot 93](https://user-images.githubusercontent.com/43567417/46246519-ca396200-c431-11e8-978f-bd7622955963.png)

**Comment by HatsyRei** [comment]
@chinwailun This is probably fixed in Issue#1 by your commit?

https://github.com/smashita/CPT341SDA/issues/1
