### ISSUE TITLE
Recipe disappeared after being edited.

### ISSUE THREAD

**Issue by Chow1218** [smashita/CPT341SDA#22]
![capture](https://user-images.githubusercontent.com/43537842/46255339-59945300-c4ce-11e8-9f88-fb7c6d3d668f.PNG)
![capture1](https://user-images.githubusercontent.com/43537842/46255310-ff938d80-c4cd-11e8-9317-9a359e16a556.PNG)

As you can see, the Recipe 1 was disappeared after " Recipe 1 successfully edited"

**Comment by SkyGo1996** [comment]
To be precise, the recipe is not disappeared. The real problem is the name of the selected recipe after edited is been save to blank name
