### ISSUE TITLE
There is no limitation in adding ingredients for the recipe

### ISSUE THREAD

**Issue by yuanhonglaw** [smashita/CPT341SDA#23]
![image](https://user-images.githubusercontent.com/43537842/46269650-28229280-c575-11e8-8393-73e1115ae16f.png)

Based on the screenshot above, user can enter as much as possible of coffee, milk, sugar, chocolate to the recipe without knowing if the inventory has that much of supplies. This is quite illogical in my perspective. I would suggest the program set some validations, either the ingredients of the recipe must be within the range of the inventory or the user must proceed to the adding inventory option before able to create a recipe that exceeds the inventory.

**Comment by HatsyRei** [comment]
@hazirah229 Your fork appears to be a few commits behind the master repo. Updating your fork and then running the program should fix the incorrect error messages.

**Comment by hazirah229** [comment]
Thanks @HatsyRei . I forgot to clone the master repo after those commits. I run the code again, and the error message was fixed.

**Comment by ansonyeap95** [comment]
The program can let the user enter the unlimited the amount of the coffee, milk, sugar and chocolate. For my suggestion is set a limitation of the adding units in recipe
