### ISSUE TITLE
Wrong error message when attempting to Make Coffee with insufficient ingredient in Inventory

### ISSUE THREAD

**Issue by NuraziraAhmad** [smashita/CPT341SDA#27]
![add recipe](https://user-images.githubusercontent.com/43541855/46571856-024f2080-c9af-11e8-899c-982aba8d5024.PNG)
This one is when I added a new recipe.

![make coffee](https://user-images.githubusercontent.com/43541855/46571875-7ab5e180-c9af-11e8-93e1-f18cca289a9d.PNG)
This one is when I want to purchase that recipe. 

I think " Insufficient funds to purchase" should not be displayed.
I think it should display something that tell the user that there is not enough unit of ingredient in the inventory. Right?

**Comment by HatsyRei** [comment]
Yep. Sounds like https://github.com/smashita/CPT341SDA/issues/4
