### ISSUE TITLE
The fourth recipe cannot be deleted.

### ISSUE THREAD

**Issue by gheewei1608** [smashita/CPT341SDA#28]
![coffeemakerissue](https://user-images.githubusercontent.com/43561828/46583345-0c911d80-ca88-11e8-89a9-d3f40fa6fb79.PNG)

Given that the maximum recipe that can be stored inside the recipe book is 4, the statement (recipe>=0 && recipe<=2) should be replaced by (recipe>=0 && recipe<=3).

**Comment by HatsyRei** [comment]
Issue appears to have been fixed by @alexleong4438 in https://github.com/smashita/CPT341SDA/pull/35. The condition is now neatly:

> if (recipe < 0 || recipe > 3) {
>         throw new NumberFormatException();
> }
