### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by MaryamSyakirah** [smashita/CPT341SDA#37]
![image](https://user-images.githubusercontent.com/43544475/46707649-70287000-cc6d-11e8-884c-23cc8bbe1d68.png)

This one I found out when i was wrong enter the number of recipe to purchase. Supposedly, I select no.1 to purchase the coffee from the coffee recipe. When I enter "s" it will ask again to select the number from 1-3 but when I enter number 1, it will come out like this.

**Comment by HatsyRei** [comment]
I can't seem to recreate the issue. Is your fork/cloned repository up to date?

**Comment by MaryamSyakirah** [comment]
wait, I try to check

**Comment by MaryamSyakirah** [comment]
Thank you for remind me to update the repository.
After I update the repository, that exception in thread "main" already disappeared. If I try to do the same thing like before, it will come out like this.
![image](https://user-images.githubusercontent.com/43544475/46708973-0bbcdf00-cc74-11e8-839d-85aa58cd1d6d.png)

 So, if I want to purchase the coffee, i need enter number "6" to make coffee again, right?
